### ISSUE TITLE
你好,请问有没有数据库里面的数据呢 没有数据运行不了哦

### ISSUE THREAD

**Issue by koun928** [ichigo-ichie27/PersonnelManagementSystem#4]

**Comment by ichigo-ichie27** [comment]
你好，很高兴你能浏览我的项目，项目中的sql文件只有数据库表的结构，我已将数据和表结构的sql文件添加为附件。由于本人能力有限，项目中还存在些许问题，如你在项目运行中遇到了问题，还请你标记出来，我们一起解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"koun928"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 晚上8:38
收件人:&nbsp;"ichigo-ichie27/PersonnelManagementSystem"<PersonnelManagementSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ichigo-ichie27/PersonnelManagementSystem] 你好,请问有没有数据库里面的数据呢 没有数据运行不了哦 (#4)





 
Closed #4.

**Comment by koun928** [comment]
> 你好，很高兴你能浏览我的项目，项目中的sql文件只有数据库表的结构，我已将数据和表结构的sql文件添加为附件。由于本人能力有限，项目中还存在些许问题，如你在项目运行中遇到了问题，还请你标记出来，我们一起解决
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"koun928"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月17日(星期三) 晚上8:38 收件人:&nbsp;"ichigo-ichie27/PersonnelManagementSystem"<PersonnelManagementSystem@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [ichigo-ichie27/PersonnelManagementSystem] 你好,请问有没有数据库里面的数据呢 没有数据运行不了哦 (#4) Closed #4. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 你好，很高兴你能浏览我的项目，项目中的sql文件只有数据库表的结构，我已将数据和表结构的sql文件添加为附件。由于本人能力有限，项目中还存在些许问题，如你在项目运行中遇到了问题，还请你标记出来，我们一起解决
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"koun928"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月17日(星期三) 晚上8:38 收件人:&nbsp;"ichigo-ichie27/PersonnelManagementSystem"<PersonnelManagementSystem@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [ichigo-ichie27/PersonnelManagementSystem] 你好,请问有没有数据库里面的数据呢 没有数据运行不了哦 (#4) Closed #4. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 谢谢你 我不是很会用GitHub  不清楚附件在哪里 能否发送到我的邮箱里面呢  qq邮箱 1570116343@qq.com
