### ISSUE TITLE
你好，能麻烦发一下数据库中的数据吗，谢谢

### ISSUE THREAD

**Issue by FaithLinxi** [ichigo-ichie27/PersonnelManagementSystem#7]

**Comment by ichigo-ichie27** [comment]
您好，很高兴收到您的来信，我已将数据库表结构和数据以附件的方式上传，请您查收




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ichigo-ichie27/PersonnelManagementSystem"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 晚上6:06
收件人:&nbsp;"ichigo-ichie27/PersonnelManagementSystem"<PersonnelManagementSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ichigo-ichie27/PersonnelManagementSystem] 你好，能麻烦发一下数据库中的数据吗，谢谢 (#7)

**Comment by FaithLinxi** [comment]
感谢你的回复，但我没找到附件，能否发送到我的邮箱里面呢，qq邮箱 1604389100@qqcom
